# Generated by Django 2.2.7 on 2019-11-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('created_on', models.DateTimeField(verbose_name='date created')),
                ('last_modified', models.DateTimeField(verbose_name='last modified')),
                ('columns', models.TextField()),
                ('rows', models.TextField()),
            ],
        ),
    ]
